


function Scrollspy() {
    return (
        <>
            <nav id="navbar-example2" className="navbar bg-body-tertiary px-3 mb-3">
                <a className="navbar-brand" href="#">Navbar</a>
                <ul className="nav nav-pills">
                    <li className="nav-item">
                        <a className="nav-link" href="#scrollspyHeading1">First</a>
                    </li>
                    <li className="nav-item">
                        <a className="nav-link" href="#scrollspyHeading2">Second</a>
                    </li>
                    <li className="nav-item dropdown">
                        <a className="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Dropdown</a>
                        <ul className="dropdown-menu">
                            <li><a className="dropdown-item" href="#scrollspyHeading3">Third</a></li>
                            <li><a className="dropdown-item" href="#scrollspyHeading4">Fourth</a></li>
                            <li><hr className="dropdown-divider"/></li>
                            <li><a className="dropdown-item" href="#scrollspyHeading5">Fifth</a></li>
                        </ul>
                    </li>
                </ul>
            </nav>
            <div data-bs-spy="scroll" data-bs-target="#navbar-example2" data-bs-root-margin="0px 0px -40%" data-bs-smooth-scroll="true" className="scrollspy-example bg-body-tertiary p-3 rounded-2" tabIndex="0">
                <h4 id="scrollspyHeading1">First heading</h4>
                <p>
                    
                tellus. Curabitur eget urna vitae turpis semper pulvinar. Ut id luctus leo, eu hendrerit eros. In quis odio venenatis, placerat dolor vitae, viverra diam. Nam nec suscipit sapien. Suspendisse bibendum erat id nunc sodales, in volutpat felis molestie. Aenean sed egestas purus, vitae iaculis nibh. In scelerisque leo id ipsum porta consectetur et quis libero. Morbi in porttitor metus, at malesuada mi. Quisque vel nisi dui. Quisque pharetra condimentum libero, et finibus nunc. Cras ornare, turpis eu rhoncus ultrices, metus nulla faucibus odio, vitae pellentesque metus turpis vel ligula. Curabitur in massa non quam malesuada malesuada id sit amet elit. Duis condimentum nulla ut mauris blandit, sed posuere ante condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque interdum nisi non finibus tempus.
                
                tellus. Curabitur eget urna vitae turpis semper pulvinar. Ut id luctus leo, eu hendrerit eros. In quis odio venenatis, placerat dolor vitae, viverra diam. Nam nec suscipit sapien. Suspendisse bibendum erat id nunc sodales, in volutpat felis molestie. Aenean sed egestas purus, vitae iaculis nibh. In scelerisque leo id ipsum porta consectetur et quis libero. Morbi in porttitor metus, at malesuada mi. Quisque vel nisi dui. Quisque pharetra condimentum libero, et finibus nunc. Cras ornare, turpis eu rhoncus ultrices, metus nulla faucibus odio, vitae pellentesque metus turpis vel ligula. Curabitur in massa non quam malesuada malesuada id sit amet elit. Duis condimentum nulla ut mauris blandit, sed posuere ante condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque interdum nisi non finibus tempus.
                
                tellus. Curabitur eget urna vitae turpis semper pulvinar. Ut id luctus leo, eu hendrerit eros. In quis odio venenatis, placerat dolor vitae, viverra diam. Nam nec suscipit sapien. Suspendisse bibendum erat id nunc sodales, in volutpat felis molestie. Aenean sed egestas purus, vitae iaculis nibh. In scelerisque leo id ipsum porta consectetur et quis libero. Morbi in porttitor metus, at malesuada mi. Quisque vel nisi dui. Quisque pharetra condimentum libero, et finibus nunc. Cras ornare, turpis eu rhoncus ultrices, metus nulla faucibus odio, vitae pellentesque metus turpis vel ligula. Curabitur in massa non quam malesuada malesuada id sit amet elit. Duis condimentum nulla ut mauris blandit, sed posuere ante condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque interdum nisi non finibus tempus.
                
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sodales, enim et condimentum aliquet, eros nunc fermentum arcu, id dignissim lacus purus ut tellus. Curabitur eget urna vitae turpis semper pulvinar. Ut id luctus leo, eu hendrerit eros. In quis odio venenatis, placerat dolor vitae, viverra diam. Nam nec suscipit sapien. Suspendisse bibendum erat id nunc sodales, in volutpat felis molestie. Aenean sed egestas purus, vitae iaculis nibh. In scelerisque leo id ipsum porta consectetur et quis libero. Morbi in porttitor metus, at malesuada mi. Quisque vel nisi dui. Quisque pharetra condimentum libero, et finibus nunc. Cras ornare, turpis eu rhoncus ultrices, metus nulla faucibus odio, vitae pellentesque metus turpis vel ligula. Curabitur in massa non quam malesuada malesuada id sit amet elit. Duis condimentum nulla ut mauris blandit, sed posuere ante condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque interdum nisi non finibus tempus.</p>
                <h4 id="scrollspyHeading2">Second heading</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sodales, enim et condimentum aliquet, eros nunc fermentum arcu, id dignissim lacus purus ut tellus. Curabitur eget urna vitae turpis semper pulvinar. Ut id luctus leo, eu hendrerit eros. In quis odio venenatis, placerat dolor vitae, viverra diam. Nam nec suscipit sapien. Suspendisse bibendum erat id nunc sodales, in volutpat felis molestie. Aenean sed egestas purus, vitae iaculis nibh. In scelerisque leo id ipsum porta consectetur et quis libero. Morbi in porttitor metus, at malesuada mi. Quisque vel nisi dui. Quisque pharetra condimentum libero, et finibus nunc. Cras ornare, turpis eu rhoncus ultrices, metus nulla faucibus odio, vitae pellentesque metus turpis vel ligula. Curabitur in massa non quam malesuada malesuada id sit amet elit. Duis condimentum nulla ut mauris blandit, sed posuere ante condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque interdum nisi non finibus tempus.
                    
                tellus. Curabitur eget urna vitae turpis semper pulvinar. Ut id luctus leo, eu hendrerit eros. In quis odio venenatis, placerat dolor vitae, viverra diam. Nam nec suscipit sapien. Suspendisse bibendum erat id nunc sodales, in volutpat felis molestie. Aenean sed egestas purus, vitae iaculis nibh. In scelerisque leo id ipsum porta consectetur et quis libero. Morbi in porttitor metus, at malesuada mi. Quisque vel nisi dui. Quisque pharetra condimentum libero, et finibus nunc. Cras ornare, turpis eu rhoncus ultrices, metus nulla faucibus odio, vitae pellentesque metus turpis vel ligula. Curabitur in massa non quam malesuada malesuada id sit amet elit. Duis condimentum nulla ut mauris blandit, sed posuere ante condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque interdum nisi non finibus tempus.
                
                tellus. Curabitur eget urna vitae turpis semper pulvinar. Ut id luctus leo, eu hendrerit eros. In quis odio venenatis, placerat dolor vitae, viverra diam. Nam nec suscipit sapien. Suspendisse bibendum erat id nunc sodales, in volutpat felis molestie. Aenean sed egestas purus, vitae iaculis nibh. In scelerisque leo id ipsum porta consectetur et quis libero. Morbi in porttitor metus, at malesuada mi. Quisque vel nisi dui. Quisque pharetra condimentum libero, et finibus nunc. Cras ornare, turpis eu rhoncus ultrices, metus nulla faucibus odio, vitae pellentesque metus turpis vel ligula. Curabitur in massa non quam malesuada malesuada id sit amet elit. Duis condimentum nulla ut mauris blandit, sed posuere ante condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque interdum nisi non finibus tempus.
                
                tellus. Curabitur eget urna vitae turpis semper pulvinar. Ut id luctus leo, eu hendrerit eros. In quis odio venenatis, placerat dolor vitae, viverra diam. Nam nec suscipit sapien. Suspendisse bibendum erat id nunc sodales, in volutpat felis molestie. Aenean sed egestas purus, vitae iaculis nibh. In scelerisque leo id ipsum porta consectetur et quis libero. Morbi in porttitor metus, at malesuada mi. Quisque vel nisi dui. Quisque pharetra condimentum libero, et finibus nunc. Cras ornare, turpis eu rhoncus ultrices, metus nulla faucibus odio, vitae pellentesque metus turpis vel ligula. Curabitur in massa non quam malesuada malesuada id sit amet elit. Duis condimentum nulla ut mauris blandit, sed posuere ante condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque interdum nisi non finibus tempus.
                </p>
                <h4 id="scrollspyHeading3">Third heading</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sodales, enim et condimentum aliquet, eros nunc fermentum arcu, id dignissim lacus purus ut tellus. Curabitur eget urna vitae turpis semper pulvinar. Ut id luctus leo, eu hendrerit eros. In quis odio venenatis, placerat dolor vitae, viverra diam. Nam nec suscipit sapien. Suspendisse bibendum erat id nunc sodales, in volutpat felis molestie. Aenean sed egestas purus, vitae iaculis nibh. In scelerisque leo id ipsum porta consectetur et quis libero. Morbi in porttitor metus, at malesuada mi. Quisque vel nisi dui. Quisque pharetra condimentum libero, et finibus nunc. Cras ornare, turpis eu rhoncus ultrices, metus nulla faucibus odio, vitae pellentesque metus turpis vel ligula. Curabitur in massa non quam malesuada malesuada id sit amet elit. Duis condimentum nulla ut mauris blandit, sed posuere ante condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque interdum nisi non finibus tempus.
                    
                tellus. Curabitur eget urna vitae turpis semper pulvinar. Ut id luctus leo, eu hendrerit eros. In quis odio venenatis, placerat dolor vitae, viverra diam. Nam nec suscipit sapien. Suspendisse bibendum erat id nunc sodales, in volutpat felis molestie. Aenean sed egestas purus, vitae iaculis nibh. In scelerisque leo id ipsum porta consectetur et quis libero. Morbi in porttitor metus, at malesuada mi. Quisque vel nisi dui. Quisque pharetra condimentum libero, et finibus nunc. Cras ornare, turpis eu rhoncus ultrices, metus nulla faucibus odio, vitae pellentesque metus turpis vel ligula. Curabitur in massa non quam malesuada malesuada id sit amet elit. Duis condimentum nulla ut mauris blandit, sed posuere ante condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque interdum nisi non finibus tempus.
                
                tellus. Curabitur eget urna vitae turpis semper pulvinar. Ut id luctus leo, eu hendrerit eros. In quis odio venenatis, placerat dolor vitae, viverra diam. Nam nec suscipit sapien. Suspendisse bibendum erat id nunc sodales, in volutpat felis molestie. Aenean sed egestas purus, vitae iaculis nibh. In scelerisque leo id ipsum porta consectetur et quis libero. Morbi in porttitor metus, at malesuada mi. Quisque vel nisi dui. Quisque pharetra condimentum libero, et finibus nunc. Cras ornare, turpis eu rhoncus ultrices, metus nulla faucibus odio, vitae pellentesque metus turpis vel ligula. Curabitur in massa non quam malesuada malesuada id sit amet elit. Duis condimentum nulla ut mauris blandit, sed posuere ante condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque interdum nisi non finibus tempus.

                </p>
                <h4 id="scrollspyHeading4">Fourth heading</h4>
                <p>
                    tellus. Curabitur eget urna vitae turpis semper pulvinar. Ut id luctus leo, eu hendrerit eros. In quis odio venenatis, placerat dolor vitae, viverra diam. Nam nec suscipit sapien. Suspendisse bibendum erat id nunc sodales, in volutpat felis molestie. Aenean sed egestas purus, vitae iaculis nibh. In scelerisque leo id ipsum porta consectetur et quis libero. Morbi in porttitor metus, at malesuada mi. Quisque vel nisi dui. Quisque pharetra condimentum libero, et finibus nunc. Cras ornare, turpis eu rhoncus ultrices, metus nulla faucibus odio, vitae pellentesque metus turpis vel ligula. Curabitur in massa non quam malesuada malesuada id sit amet elit. Duis condimentum nulla ut mauris blandit, sed posuere ante condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque interdum nisi non finibus tempus.
                    
                    tellus. Curabitur eget urna vitae turpis semper pulvinar. Ut id luctus leo, eu hendrerit eros. In quis odio venenatis, placerat dolor vitae, viverra diam. Nam nec suscipit sapien. Suspendisse bibendum erat id nunc sodales, in volutpat felis molestie. Aenean sed egestas purus, vitae iaculis nibh. In scelerisque leo id ipsum porta consectetur et quis libero. Morbi in porttitor metus, at malesuada mi. Quisque vel nisi dui. Quisque pharetra condimentum libero, et finibus nunc. Cras ornare, turpis eu rhoncus ultrices, metus nulla faucibus odio, vitae pellentesque metus turpis vel ligula. Curabitur in massa non quam malesuada malesuada id sit amet elit. Duis condimentum nulla ut mauris blandit, sed posuere ante condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque interdum nisi non finibus tempus.
                    
                    tellus. Curabitur eget urna vitae turpis semper pulvinar. Ut id luctus leo, eu hendrerit eros. In quis odio venenatis, placerat dolor vitae, viverra diam. Nam nec suscipit sapien. Suspendisse bibendum erat id nunc sodales, in volutpat felis molestie. Aenean sed egestas purus, vitae iaculis nibh. In scelerisque leo id ipsum porta consectetur et quis libero. Morbi in porttitor metus, at malesuada mi. Quisque vel nisi dui. Quisque pharetra condimentum libero, et finibus nunc. Cras ornare, turpis eu rhoncus ultrices, metus nulla faucibus odio, vitae pellentesque metus turpis vel ligula. Curabitur in massa non quam malesuada malesuada id sit amet elit. Duis condimentum nulla ut mauris blandit, sed posuere ante condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque interdum nisi non finibus tempus.
                    
                    tellus. Curabitur eget urna vitae turpis semper pulvinar. Ut id luctus leo, eu hendrerit eros. In quis odio venenatis, placerat dolor vitae, viverra diam. Nam nec suscipit sapien. Suspendisse bibendum erat id nunc sodales, in volutpat felis molestie. Aenean sed egestas purus, vitae iaculis nibh. In scelerisque leo id ipsum porta consectetur et quis libero. Morbi in porttitor metus, at malesuada mi. Quisque vel nisi dui. Quisque pharetra condimentum libero, et finibus nunc. Cras ornare, turpis eu rhoncus ultrices, metus nulla faucibus odio, vitae pellentesque metus turpis vel ligula. Curabitur in massa non quam malesuada malesuada id sit amet elit. Duis condimentum nulla ut mauris blandit, sed posuere ante condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque interdum nisi non finibus tempus.
                    </p>
                <h4 id="scrollspyHeading5">Fifth heading</h4>
                <p>
                    tellus. Curabitur eget urna vitae turpis semper pulvinar. Ut id luctus leo, eu hendrerit eros. In quis odio venenatis, placerat dolor vitae, viverra diam. Nam nec suscipit sapien. Suspendisse bibendum erat id nunc sodales, in volutpat felis molestie. Aenean sed egestas purus, vitae iaculis nibh. In scelerisque leo id ipsum porta consectetur et quis libero. Morbi in porttitor metus, at malesuada mi. Quisque vel nisi dui. Quisque pharetra condimentum libero, et finibus nunc. Cras ornare, turpis eu rhoncus ultrices, metus nulla faucibus odio, vitae pellentesque metus turpis vel ligula. Curabitur in massa non quam malesuada malesuada id sit amet elit. Duis condimentum nulla ut mauris blandit, sed posuere ante condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque interdum nisi non finibus tempus.
                    
                    tellus. Curabitur eget urna vitae turpis semper pulvinar. Ut id luctus leo, eu hendrerit eros. In quis odio venenatis, placerat dolor vitae, viverra diam. Nam nec suscipit sapien. Suspendisse bibendum erat id nunc sodales, in volutpat felis molestie. Aenean sed egestas purus, vitae iaculis nibh. In scelerisque leo id ipsum porta consectetur et quis libero. Morbi in porttitor metus, at malesuada mi. Quisque vel nisi dui. Quisque pharetra condimentum libero, et finibus nunc. Cras ornare, turpis eu rhoncus ultrices, metus nulla faucibus odio, vitae pellentesque metus turpis vel ligula. Curabitur in massa non quam malesuada malesuada id sit amet elit. Duis condimentum nulla ut mauris blandit, sed posuere ante condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque interdum nisi non finibus tempus.
                    
                    tellus. Curabitur eget urna vitae turpis semper pulvinar. Ut id luctus leo, eu hendrerit eros. In quis odio venenatis, placerat dolor vitae, viverra diam. Nam nec suscipit sapien. Suspendisse bibendum erat id nunc sodales, in volutpat felis molestie. Aenean sed egestas purus, vitae iaculis nibh. In scelerisque leo id ipsum porta consectetur et quis libero. Morbi in porttitor metus, at malesuada mi. Quisque vel nisi dui. Quisque pharetra condimentum libero, et finibus nunc. Cras ornare, turpis eu rhoncus ultrices, metus nulla faucibus odio, vitae pellentesque metus turpis vel ligula. Curabitur in massa non quam malesuada malesuada id sit amet elit. Duis condimentum nulla ut mauris blandit, sed posuere ante condimentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque interdum nisi non finibus tempus.
                    </p>
            </div>
        </>
    )
}

export default Scrollspy;